use_frameworks!

platform :ios, '10.0'

target 'CommonSecurity_Example' do
  pod 'CommonSecurity', :path => 'https://github.com/ankitkumarg1/CommonSecurity/'

  target 'CommonSecurity_Tests' do
    inherit! :search_paths

    
  end
end
